### ISSUE TITLE
[PE-D] Mismatch in syntax of command and UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T17-2/tp#213]
Following up on the issue for the Find command, I realized that the keywords are separated by " , " instead of " | ". `find spaghetti, western, garlic` returns with the recipes as shown in the image.

![image.png](https://raw.githubusercontent.com/YiFei2/ped/main/files/645ad778-8db1-4ed4-8a49-13af919168c2.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: YiFei2/ped#9

**Comment by yusufaine** [comment]
Duplicate issue of find using comma instead of pipe.

Issue was fixed but wrong JAR file was uploaded.
