### ISSUE TITLE
[docs-DG] update undo command as a future command

### ISSUE THREAD

**Issue by yusufaine** [AY2122S2-CS2103T-T17-2/tp#225]
@yusufaine honestly I think undo is sufficient to solve this issue since this suggestion is referring to cases where the user made a mistake. We don't need an advanced reset to save the current point if we can undo any mistakes.

_Originally posted by @blaketingyu in https://github.com/AY2122S2-CS2103T-T17-2/tp/issues/217#issuecomment-1088825422_

**Comment by gigituang** [comment]
We can have a section for future improvements in our UG?

**Comment by yusufaine** [comment]
To include:

User Guide (Tentative -- TCB with Aileen):
* Future features to include
  - [ ] Improved find command
  - [ ] Undo command (undo previous action)
  - [ ] Scale command (up/down scale recipes)

Developer Guide:
* Future features to include
  - [ ] Improved find command
  - [ ] Undo command (undo previous action)
  - [ ] Scale command (up/down scale recipes)

**Comment by yusufaine** [comment]
Closed in #255 

Explained in DG of future feature for undo/redo and enhance find command
