### ISSUE TITLE
[Doc-Command Summary-view] Command summary shows wrong command format

### ISSUE THREAD

**Issue by aidanaden** [AY2122S2-CS2103T-T17-2/tp#251]
[Doc-Command Summary-view] Command summary shows wrong command format
severity: Low

Suggestion: `view -x <recipe number from list>`

_Originally posted by @pyk595 in https://github.com/AY2122S2-CS2103T-T17-2/tp/issues/240#issuecomment-1092930918_

**Comment by yusufaine** [comment]
Fixed in #256
