### ISSUE TITLE
fix(RecipeBookSyntax): bug with current prefix choice

### ISSUE THREAD

**Issue by Oddcorner** [AY2122S2-CS2103T-T17-2/tp#56]
Given the prefix standards and assuming the use of ArugmentMultimap/ArgumentTokenizer as is, the following bug is present.

An input of ` -ss: 1` which should be interpreted as "serving size of 1", would instead be tokenized twice as both `-ss: 1` and `-s s:1` or a "step: s:1" by the current implementation of ArgumentTokenizer.tokenize().

This causes a StringIndexOutOfBoundsException to be thrown by ArgumentTonkenizer which is incorrect behaviour.

**Comment by Oddcorner** [comment]
Bleh, I misread the prefix standards. Disregard.

**Comment by yusufaine** [comment]
> Bleh, I misread the prefix standards. Disregard.

@Oddcorner Actually regarding this, I'm still not sold on `-ss` being a Prefix for `ServingSize` but not sure what to assign it to
